Hud Overlays Patch
ValidHunters/SubversionalExamplePatch pull request #1
Opened 2024-05-13 18:00 UTC by PetrosanW

Includes all hud overlays for the player

2024-05-13 19:57 UTC, Subversionary commented
Оставлено на решение @mynameundefined

2024-05-23 14:45 UTC, mynameundefined commented
> Left up to @mynameundefined My opinion is that these patches should be kept in the repositories of the people making them.

i agree

2024-05-24 09:34 UTC, noverd requested changes
Это должно быть как делал я в своем патче. Посмотри .csproj SimpleCommand, там сделано чтоб меньше мусора было.

2024-05-24 09:36 UTC, noverd requested changes
Это должно [.csproj] быть как делал я в своем патче. Посмотри .csproj SimpleCommand, там сделано чтоб меньше мусора было.

2024-05-24 09:36 UTC, noverd commented on HudOverlaysPatch/HudOverlaysPatch.csproj
Если что я про вот это.

2024-05-24 09:36 UTC, noverd commented on HudOverlaysPatch/SubPatch.cs
Переименуй файл в нормально название.

2024-05-24 09:42 UTC, Subversionary commented
> > Left up to @mynameundefined My opinion is that these patches should be kept in the repositories of the people making them.
> 
> i agree

2024-05-24 09:42 UTC, closed without merging